// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

/****************************************************************************************
 *                            NOTICE: AUTO-GENERATED                                    *
 ****************************************************************************************
 * This file is automatically generated by script "./src/question/generator.ts".        *
 * Please don't manually change its contents, as any modifications will be overwritten! *
 ***************************************************************************************/

import { CLICommandOption, CLICommandArgument } from "@microsoft/teamsfx-api";

export const removeSharedAccessOptions: CLICommandOption[] = [
  {
    name: "users",
    type: "array",
    description: "Select users to remove access",
    required: true,
    skipValidation: true,
  },
];
export const removeSharedAccessArguments: CLICommandArgument[] = [];
