// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

/****************************************************************************************
 *                            NOTICE: AUTO-GENERATED                                    *
 ****************************************************************************************
 * This file is automatically generated by script "./src/question/generator.ts".        *
 * Please don't manually change its contents, as any modifications will be overwritten! *
 ***************************************************************************************/

import { CLICommandOption, CLICommandArgument } from "@microsoft/teamsfx-api";

export const ShareOptions: CLICommandOption[] = [
  {
    name: "option",
    type: "string",
    description: "option",
    required: true,
    choices: ["share-app", "share-with-users"],
  },
  {
    name: "users",
    type: "string",
    description: "Enter user emails (separated by commas)",
  },
];
export const ShareArguments: CLICommandArgument[] = [];
